### ISSUE TITLE
Cosys-Integration: HTTP-Status Code Handling

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-project#544] opened 2023-02-28 10:48 UTC
**Is your feature request related to a problem? Please describe.**
The Cosys-Int doesn't handle Http-Status Codes, such as 40X and 50X.

**Describe the solution you'd like**
Throw BPM-Error oder Incident on HTTP Error Codes

**Describe alternatives you've considered**
-

**Additional context**
Internal Ref: https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/215

The API is generated by the OpenAPI Maven Generator:
https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-integrations/digiwf-cosys-integration/digiwf-cosys-integration-client/pom.xml#L99

Here is the missing errorhandling:
https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-integrations/digiwf-cosys-integration/digiwf-cosys-integration-client/src/main/java/io/muenchendigital/digiwf/cosys/integration/gen/api/GenerationApi.java#L162

There should be some `onStatus` Handlers before `bodyToMono(..)`

Es muss eine andere Methode verwendet werden: `generatePdfWithResponseSpec`

Siehe: https://github.com/OpenAPITools/openapi-generator/pull/12843

**Acceptance criteria**
What conditions must be satisfied to be accepted

- [ ] Camunda Incident on 404 an other HTTP Errors

**Priority**
When is the feature needed

**Comment by lmoesle** [comment] 2023-03-02 15:18
Duplicate of https://github.com/it-at-m/digiwf-project/issues/534 

I will close this issue and add the Infos to https://github.com/it-at-m/digiwf-core/issues/165

**Closed as completed by lmoesle** 2023-03-02 15:18 UTC
Labels: enhancement, refinement
